# Generated by Django 3.1.1 on 2020-09-20 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='zip_code',
            new_name='zip',
        ),
    ]
